### ISSUE TITLE
Request for IceCat Support

### ISSUE THREAD

**Issue by sproggit** [floccusaddon/floccus#981]
### Is your feature request related to a problem? Please describe.
I am trying to use Floccus with IceCat 60.8.0esr (64-bit) on Linux Mint 20.1... I have Floccus working perfectly with Firefox 93.0 on the same OS platform, but with the recent changes to Firefox, I'm thinking of leaving the platform and don't like the idea of moving to Chrome. 
I have successfully installed the Floccus Plug-In on IceCat and I have successfully exported my FireFox Floccus config using the "Export Accounts" function. Viewing the resultant "floccus.export.json" file in a text editors shows that it looks good, with no format or syntax errors. 
When I try to import in IceCat, I get a popup message, "t.text is not a function". 
However, I must note in passing that IceCat uses "LibreJS", which I suspect is a different version of Javascript from Firefox, so I am wondering if this is the reason for the error. When I check the default Extensions for IceCat I notice that there are 6 plug-ins specifically added to make LibreJS compatible with various web sites and services, but simply disabling LibreJS results in the exact same error message. 

### Describe the solution you'd like
Apologies if I've been stupid and missed something to correct the error, but I'm hoping someone can take a look and figure out how to make Floccus work with IceCat please? 

### Describe alternatives you've considered
Realistically, given how valuable Floccus is, my only real choices are 1) stick with Firefox [not ideal given their apparent desire to sell their soul] or go with Chrome [um, No]. 

### Additional context
Just to add that I'm sorry in advance if this has been covered before - I did search but didn't find anything on this topic.

**Comment by mnalis** [comment]
[LibreJS](https://www.gnu.org/software/librejs/) should not be related to the problem, though. It is extension which _"blocks nonfree nontrivial JavaScript while allowing JavaScript that is free and/or trivial"_ (and additional LibreJS-related addons provide JavaScript replacements for some popular websites to use instead of non-free/obfuscated javascript code provided by those sites by default)

**Comment by sproggit** [comment]
> Hi!
> 
> Does IceCat support web extensions at all? IIRC firefox started support in v68?

Hello Marcel, it looks as though IceCat does support Web Extensions, but having said that, the FSF page on the topic isn't entirely clear. Here's a link to what I found:-
https://directory.fsf.org/wiki/Free_Software_Directory:IceCat_WebExtensions_(proposed)/About

Unfortunately, digging a bit deeper it looks as though IceCat hasn't received any update since 2019, which rather suggests that it is a dead or dying project. I was mainly looking to see if IceCat would be a viable alternative to FireFox [as Firefox is adding more and more intrusive content]. But if it isn't being maintained, that would likely be a problem. 

I am sorry for wasting your time with this question.
