### ISSUE TITLE
WebDAV stopped working on Android with 5.0.2

### ISSUE THREAD

**Issue by kolinger** [floccusaddon/floccus#1455]
### Which version of floccus are you using?

5.0.2

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 10

### What kind of WebDAV server are you using? (if relevant)

nginx

### Describe the Bug

Sync doesn't work and floccus shows "Check your network connection and your profile details" even when network works fine and profile details are correct (I can connect to WebDAV server via other app without issue). Profile details were checked and were imported from previous version where exact details work fine.

Details from console:

NullPointerException happens in underlying HTTP library at WebDav.ts/downloadFileNative. No input for Http.request is null so this is strange.

```
2023-12-09T17:16:46.947Z Error Caught 
native.js:5907 2023-12-09T17:16:46.947Z { [Error: NullPointerException] code: undefined }
native.js:93776 Error: NullPointerException
    at returnResult ((index):915:32)
    at win.androidBridge.onmessage ((index):890:21)
native.js:88639 Error: E017: Network error: Check your network connection and your profile details
    at NetworkError.FloccusError [as constructor] (native.js:87811:28)
    at new NetworkError (native.js:87980:28)
    at WebDavAdapter.<anonymous> (native.js:93777:31)
    at step (native.js:93218:23)
    at Object.throw (native.js:93199:53)
    at rejected (native.js:93191:65)
```

### Expected Behavior

Sync should work and floccus shouldn't show misleading network error when null pointer is happening.

### To Reproduce

WebDav on Android should do the trick.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Mmh, this might be a capacitor bug :(

**Comment by kolinger** [comment]
Likely since nothing what floccus passed is null or invalid, URL is valid, auth header is valid and rest are strings so there is no reason to get NullPointerException yet it happens even after reinstall and after downgrade exact code works just fine with identical profile details.

**Comment by marcelklehr** [comment]
I think I even fixed the bug once when testing some custom java code, but thought I had inadvertantly introduced it with my modifications. I'll publish a patch tomorrow

**Comment by kolinger** [comment]
WebDAV works again with 7133d28 👍

**Comment by kolinger** [comment]
I do experiment with source but I'm no JS programmer, all my experience is in other languages (Python, PHP, Java, Go, C++, ...) so I don't even understand how this whole Vue thing works. I'm more server-side person thus this JS magic limits my ability to contribute. Right know I just trying to understand how things works with this platform.
